import { accountBalanceIcon, articleIcon, bagIcon, balanceIcon, carIcon, devicesIcon, ecoIcon, familyIcon, locationIcon, oldmenIcon, policeIcon, workIcon } from "../common/Icons";

export const cards: { icon: any; titulo: string; descricao: any[] }[] = [
    {
      icon: workIcon,
      titulo: "Direito do Trabalho",
      descricao: [
        "Horas extras e jornada excessiva de trabalho;",
        "Acúmulo e desvio de função;",
        "Falta de registro em carteira de trabalho;",
        "Danos morais;",
        "Verbas Rescisórias;",
        "Demissão indevida por Justa Causa;",
        "Insalubridade e Periculosidade;",
      ],
    },
    {
      icon: bagIcon,
      titulo: "Direito do Consumidor",
      descricao: [
        "Horas extras e jornada excessiva de trabalho",
        "Acúmulo e desvio de função",
        "Falta de registro em carteira de trabalho",
        "Danos morais",
        "Verbas Rescisórias",
        "Demissão indevida por Justa Causa",
        "Insalubridade e Periculosidade",
      ],
    },
    {
      icon: oldmenIcon,
      titulo: "Direito Previdenciário",
      descricao: [
        "Horas extras e jornada excessiva de trabalho",
        "Acúmulo e desvio de função",
        "Falta de registro em carteira de trabalho",
        "Danos morais",
        "Verbas Rescisórias",
        "Demissão indevida por Justa Causa",
        "Insalubridade e Periculosidade",
      ],
    },
    {
      icon: familyIcon,
      titulo: "Direito de Família",
      descricao: [
        "Horas extras e jornada excessiva de trabalho",
        "Acúmulo e desvio de função",
        "Falta de registro em carteira de trabalho",
        "Danos morais",
        "Verbas Rescisórias",
        "Demissão indevida por Justa Causa",
        "Insalubridade e Periculosidade",
      ],
    },
    {
      icon: carIcon,
      titulo: "Direito de Trânsito",
      descricao: [
        "Horas extras e jornada excessiva de trabalho",
        "Acúmulo e desvio de função",
        "Falta de registro em carteira de trabalho",
        "Danos morais",
        "Verbas Rescisórias",
        "Demissão indevida por Justa Causa",
        "Insalubridade e Periculosidade",
      ],
    },
    {
      icon: locationIcon,
      titulo: "Direito Imobiliário",
      descricao: [
        "Horas extras e jornada excessiva de trabalho",
        "Acúmulo e desvio de função",
        "Falta de registro em carteira de trabalho",
        "Danos morais",
        "Verbas Rescisórias",
        "Demissão indevida por Justa Causa",
        "Insalubridade e Periculosidade",
      ],
    },
    {
      icon: policeIcon,
      titulo: "Direito Criminal",
      descricao: [
        "Horas extras e jornada excessiva de trabalho",
        "Acúmulo e desvio de função",
        "Falta de registro em carteira de trabalho",
        "Danos morais",
        "Verbas Rescisórias",
        "Demissão indevida por Justa Causa",
        "Insalubridade e Periculosidade",
      ],
    },
    {
      icon: articleIcon,
      titulo: "Direito Civil (Contratos)",
      descricao: [
        "Horas extras e jornada excessiva de trabalho",
        "Acúmulo e desvio de função",
        "Falta de registro em carteira de trabalho",
        "Danos morais",
        "Verbas Rescisórias",
        "Demissão indevida por Justa Causa",
        "Insalubridade e Periculosidade",
      ],
    },
    {
      icon: accountBalanceIcon,
      titulo: "Direito Administrativo",
      descricao: [
        "Horas extras e jornada excessiva de trabalho",
        "Acúmulo e desvio de função",
        "Falta de registro em carteira de trabalho",
        "Danos morais",
        "Verbas Rescisórias",
        "Demissão indevida por Justa Causa",
        "Insalubridade e Periculosidade",
      ],
    },
    {
      icon: ecoIcon,
      titulo: "Direito Ambiental",
      descricao: [
        "Horas extras e jornada excessiva de trabalho",
        "Acúmulo e desvio de função",
        "Falta de registro em carteira de trabalho",
        "Danos morais",
        "Verbas Rescisórias",
        "Demissão indevida por Justa Causa",
        "Insalubridade e Periculosidade",
      ],
    },
    {
      icon: devicesIcon,
      titulo: "StartUp",
      descricao: [
        "Horas extras e jornada excessiva de trabalho",
        "Acúmulo e desvio de função",
        "Falta de registro em carteira de trabalho",
        "Danos morais",
        "Verbas Rescisórias",
        "Demissão indevida por Justa Causa",
        "Insalubridade e Periculosidade",
      ],
    },
    {
      icon: balanceIcon,
      titulo: "Atuação em Segundo Grau",
      descricao: [
        "Horas extras e jornada excessiva de trabalho",
        "Acúmulo e desvio de função",
        "Falta de registro em carteira de trabalho",
        "Danos morais",
        "Verbas Rescisórias",
        "Demissão indevida por Justa Causa",
        "Insalubridade e Periculosidade",
      ],
    },
  ];