import { initSeo } from "remix-seo";

export const { getSeo, getSeoMeta, getSeoLinks } = initSeo({
  // Pass any SEO defaults for your site here.
  // If individual routes do not provide their own meta and link tags,
  // the tags generated by the defaults will be used.
  title: "Conceição Advogados",
  titleTemplate: "%s | Advocacia em Santa Maria",
  description:
  "Obtenha assessoria jurídica especializada e soluções eficientes em diversas áreas do direito com o nosso escritório de advocacia. Equipe experiente e comprometida.",
});
